#!/bin/sh
set -e

case "$1" in
    configure)
        if command -v glib-compile-schemas >/dev/null 2>&1; then
            glib-compile-schemas \
                /usr/share/gnome-shell/extensions/real-calendar@boobuh.github.io/schemas
        fi
        ;;
esac

#DEBHELPER#

exit 0
